[package]
name = "tts_migrations"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

[dependencies]
toml = "0.8"

sqlx.workspace = true
anyhow.workspace = true

tts_core = { path = "../tts_core" }
